version: '3.8'

services:
  streaming-service:
    image: streaming-service:600
    build:
      context: ./streaming_service
      dockerfile: Dockerfile
    env_file:
      - .dev.env
    ports:
      - "8000:8000"

  data-service:
    image: data-service:600
    build:
      context: ./data_service
      dockerfile: Dockerfile
    env_file:
      - .dev.env
    ports:
      - "8001:8000"

  redis:
    image: redis:latest
    command: redis-server --requirepass redistest123
    env_file:
      - .dev.env
