# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory in the container to /app
WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
COPY data_service/requirements.txt .
RUN pip install -r requirements.txt

# Add the obfuscated code into the container at /app
# Assume dist/streaming_service contains the obfuscated main.py and src/
COPY dist/data_service/ /app/
COPY dist/data_service/data_service/ /app/

# Expose port 8000 for the app
EXPOSE 8000

# Define the command to run the app using uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
